# Generated by Django 2.0.8 on 2019-10-08 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rack',
            name='idc_num',
        ),
        migrations.AddField(
            model_name='rack',
            name='idc',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='cmdb.Idc', verbose_name='所属机房'),
        ),
        migrations.AddField(
            model_name='rack',
            name='number',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='size',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='U型'),
        ),
    ]
