# Generated by Django 2.0.8 on 2019-10-08 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20191008_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='user',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
    ]
