# Generated by Django 2.0.8 on 2019-10-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20191008_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rack',
            name='address',
        ),
        migrations.AddField(
            model_name='rack',
            name='remark',
            field=models.TextField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='idc',
            name='address',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='idc',
            name='remark',
            field=models.TextField(max_length=32, null=True),
        ),
    ]
