# Generated by Django 2.0.8 on 2019-09-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idc',
            name='price',
            field=models.CharField(blank=True, default='0', max_length=64, null=True),
        ),
    ]
