# Generated by Django 2.0.8 on 2019-09-18 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_idc_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idc',
            options={'ordering': ['-id']},
        ),
    ]
